AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  Deploy this lambda to a Greengrass core where it will send a hello world
  message to a topic
Resources:
  greengrasshelloworldnodejs:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: .
      Description: >-
        Deploy this lambda to a Greengrass core where it will send a hello world
        message to a topic
      MemorySize: 128
      Timeout: 3
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'ses:SendBounce'
              Resource: '*'
