AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Demonstrate a basic trivia skill built with the ASK NodeJS SDK
Resources:
  alexaskillkitsdktriviaskill:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: .
      Description: Demonstrate a basic trivia skill built with the ASK NodeJS SDK
      MemorySize: 128
      Timeout: 7
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'sns:Publish'
              Resource: 'arn:aws:sns:*:*:*'
