AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  An AWS Lambda function that throws an error. AWS Step Functions state machines
  can be configured to handle (catch or retry) this error.
Resources:
  stepfunctionserrorpython:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      CodeUri: .
      Description: >-
        An AWS Lambda function that throws an error. AWS Step Functions state
        machines can be configured to handle (catch or retry) this error.
      MemorySize: 128
      Timeout: 3
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'cloudwatch:PutMetricData'
              Resource: '*'
            - Effect: Allow
              Action:
                - 'ec2:DescribeRegions'
                - 'ec2:DescribeVpnConnections'
              Resource: '*'
