# Enable container based builds
sudo: false
dist: xenial   # required for Python >= 3.7
language: python

matrix:
  include:
    - python: 3.7
      env:
        - TOXENV=py37
    - python: 3.6
      env:
        - TOXENV=py36
    - python: 2.7
      env:
        - TOXENV=py27


install:
# Install the code requirements
- make init

# Install Docs requirements

script:
# Runs unit tests
- tox
