version: 1.0.{build}
image: Ubuntu

environment:
  matrix:
  - TOXENV: py37
    PYTHON_VERSION: '3.7'
  - TOXENV: py38
    PYTHON_VERSION: '3.8'
  - TOXENV: py39
    PYTHON_VERSION: '3.9'
  - TOXENV: py310
    PYTHON_VERSION: '3.10'

build: off

install:
- sh: "source ${HOME}/venv${PYTHON_VERSION}/bin/activate"
- sh: "python --version"
- make init

test_script:
- make integ-test

