Parameters:
  SarApplicationId:
    Type: String

Mappings:
  SARApplication:
    us-east-1:
      SemanticVersion: 1.0.3
    us-east-2:
      SemanticVersion: 1.0.3
    us-west-1:
      SemanticVersion: 1.0.3
    us-west-2:
      SemanticVersion: 1.0.3
    eu-central-1:
      SemanticVersion: 1.0.3
    eu-west-1:
      SemanticVersion: 1.0.3
    eu-west-2:
      SemanticVersion: 1.0.3
    eu-west-3:
      SemanticVersion: 1.0.3
    ap-south-1:
      SemanticVersion: 1.0.3
    ap-northeast-1:
      SemanticVersion: 1.0.3
    ap-northeast-2:
      SemanticVersion: 1.0.3
    ap-southeast-1:
      SemanticVersion: 1.0.3
    ap-southeast-2:
      SemanticVersion: 1.0.3
    ca-central-1:
      SemanticVersion: 1.0.3
    sa-east-1:
      SemanticVersion: 1.0.3

Resources:
  MyNestedApp:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId:
          Ref: SarApplicationId
        SemanticVersion:
          Fn::FindInMap:
          - SARApplication
          - { Ref: 'AWS::Region' }
          - SemanticVersion
      Parameters:
        IdentityNameParameter: test
      NotificationARNs:
        - Ref: MySns

  MySns:
    Type: AWS::SNS::Topic