Parameters:
  SemanticVersion:
    Type: String
    Default: 1.0.2

Mappings:
  SARApplication:
    us-east-1:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:077246666028:applications/hello-world-python3
    us-east-2:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:077246666028:applications/hello-world-python3
    us-west-1:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:077246666028:applications/hello-world-python3
    us-west-2:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:077246666028:applications/hello-world-python3
    eu-central-1:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:077246666028:applications/hello-world-python3
    eu-west-1:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:077246666028:applications/hello-world-python3
    eu-west-2:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:077246666028:applications/hello-world-python3
    eu-west-3:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:077246666028:applications/hello-world-python3
    ap-south-1:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:077246666028:applications/hello-world-python3
    ap-northeast-1:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:077246666028:applications/hello-world-python3
    ap-northeast-2:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:077246666028:applications/hello-world-python3
    ap-southeast-1:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:077246666028:applications/hello-world-python3
    ap-southeast-2:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:077246666028:applications/hello-world-python3
    ca-central-1:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:077246666028:applications/hello-world-python3
    sa-east-1:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:077246666028:applications/hello-world-python3

Resources:
  MyNestedApp:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId:
          Fn::FindInMap:
          - SARApplication
          - {Ref: 'AWS::Region'}
          - ApplicationId
        SemanticVersion:
          Ref: SemanticVersion
      Parameters:
        IdentityNameParameter: test
      NotificationARNs:
        - Ref: MySns

  MySns:
    Type: AWS::SNS::Topic