
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: ${codeuri}
      DeadLetterQueue:
        Type: SQS
        TargetArn:
          Fn::GetAtt: ["MyQueue", "Arn"]

  MyQueue:
    Type: AWS::SQS::Queue
