Resources:
  MyNestedApp:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:077246666028:applications/hello-world-python3
        SemanticVersion: 1.0.2
      Parameters:
        IdentityNameParameter: test
