Conditions:
  MyCondition:
    Fn::Equals:
      - true
      - false
Resources:
  MyLambdaFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: ${codeuri}
      Handler: hello.handler
      Runtime: python3.8
      AutoPublishAlias: live
      DeploymentPreference:
        Type: Linear10PercentEvery3Minutes
        Alarms:
          Fn::If:
            - MyCondition
            - - Alarm1
              - Alarm2
              - Alarm3
            - - Alarm1
              - Alarm5
