Resources:
    MyLambdaFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: index.handler
            Runtime: nodejs12.x
            CodeUri: ${codeuri}
            MemorySize: 128
            EphemeralStorage:
              Size: 1024
            Policies:
                - AWSLambdaRole
                - AmazonS3ReadOnlyAccess
            Environment:
                Variables:
                    Name: Value
                    Name2: Value2