AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Blueprint for API Gateway custom authorizers, implemented in NodeJS.'
Resources:
  apigatewayauthorizernodejs:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: .
      Description: 'Blueprint for API Gateway custom authorizers, implemented in NodeJS.'
      MemorySize: 256
      Timeout: 5
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'sns:Publish'
              Resource: 'arn:aws:sns:*:*:*'
