AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Schedules a recurring Amazon Inspector assessment run
Resources:
  inspectorscheduledrun:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: .
      Description: Schedules a recurring Amazon Inspector assessment run
      MemorySize: 128
      Timeout: 10
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'sns:ListSubscriptionsByTopic'
                - 'sns:CreateTopic'
                - 'sns:SetTopicAttributes'
                - 'sns:Subscribe'
                - 'sns:Publish'
              Resource: '*'
      Environment:
        Variables:
          assessmentTemplateArn: <enter value here>
