Parameters:
  MyDomainName: 
    Type: String
    Default: another-example.com

  MyDomainCert: 
    Type: String
    Default: another-api-arn

Globals:
  Api:
    Domain:
      DomainName: !Ref MyDomainName
      CertificateArn: !Ref MyDomainCert
      EndpointConfiguration: 'REGIONAL'
      BasePath: ['/get']

Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      InlineCode: |
        exports.handler = async (event) => {
          const response = {
            statusCode: 200,
            body: JSON.stringify('Hello from Lambda!'),
          };
          return response;
        };
      Handler: index.handler
      Runtime: nodejs8.10
      Events:
        ImplicitGet:
          Type: Api
          Properties:
            Method: Get
            Path: /get
