AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Conditions:
  C1:
    Fn::Equals:
      - true
      - true
Globals:
  Api:
    Auth:
      ResourcePolicy:
        CustomStatements:
          Fn::If:
            - C1
            - Principal: '*'
              Effect: Allow
              Action: execute-api:Invoke
              Resource: 
                - execute-api:/Prod/PUT/get
              Condition: 
                IpAddress:
                  aws:SourceIp: 1.2.3.4
            - Principal: '*'
              Effect: Allow
              Action: execute-api:Invoke
              Resource: 
                - execute-api:/Prod/PUT/get
              Condition: 
                IpAddress:
                  aws:SourceIp: 5.6.7.8
        # OR you can use the following
        # IpRangeBlacklist: ['1.2.3.4']
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      InlineCode: |
        exports.handler = async (event) => {
          const response = {
            statusCode: 200,
            body: JSON.stringify('Hello from Lambda!'),
          };
          return response;
        };
      Handler: index.handler
      Runtime: nodejs12.x
      Events:
        Api:
          Type: Api
          Properties:
            Method: Put
            Path: /get
