Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionUri: ${definitionuri}
      MethodSettings: [{LoggingLevel: INFO, MetricsEnabled: true, DataTraceEnabled: true,
          ResourcePath: /*, HttpMethod: '*'}]
Metadata:
  SamTransformTest: true
