Resources:
  TriggerStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: EXPRESS
      Definition:
        StartAt: PutDDB
        States:
          PutDDB:
            Type: Task
            Resource: !Sub arn:${AWS::Partition}:states:::dynamodb:putItem
            Parameters:
              TableName: !Ref MyTable
              Item:
                Id:
                  S: some-value
            End: True
      Policies:
        - LambdaInvokePolicy:
            FunctionName: "SomethingIsNotStateMachineFunction"

  MyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "Id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "Id"
          KeyType: "HASH"

  MyConnector:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: TriggerStateMachine
      Destination:
        Id: MyTable
      Permissions:
        - Write
