Resources:
  Bucket:
    Type: AWS::S3::Bucket
    

  TriggerStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: EXPRESS
      Definition:
        StartAt: ListBucket
        States:
          ListBucket:
            Type: Task
            Parameters: 
              Bucket: !Ref Bucket
            Resource: "arn:aws:states:::aws-sdk:s3:listObjectsV2"
            End: true
      Policies:
        - LambdaInvokePolicy:
            FunctionName: "SomethingIsNotStateMachineFunction"

  MyConnector:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: TriggerStateMachine
      Destination:
        Id: Bucket
      Permissions:
        - Read