Resources:
  MyLambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: ${codeuri}
      Handler: index.handler
      Runtime: python2.7
      AutoPublishAlias: Live
      DeploymentPreference:
        Type: Canary10Percent5Minutes
