Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      InlineCode: |
        exports.handler = async (event) => {
          const response = {
            statusCode: 200,
            body: JSON.stringify('Hello from Lambda!'),
          };
          return response;
        };
      Handler: index.handler
      Runtime: nodejs14.x
      Events:
        ImplicitGet:
          Type: HttpApi
          Properties:
            Method: Get
            Path: /get
            ApiId: 
              Ref: MyApi
        ImplicitPost:
          Type: HttpApi
          Properties:
            Method: Post
            Path: /post
            ApiId: 
              Ref: MyApi
  MyApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      DisableExecuteApiEndpoint: False
      StageName: Prod
Outputs:
  ApiId:
    Value:
      Ref: MyApi  