AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  Blueprint for redirecting unauthenticated users to sign-in page; triggered by
  CloudFront viewer-request event.
Resources:
  cloudfrontredirectunauthenticatedusers:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: .
      Description: >-
        Blueprint for redirecting unauthenticated users to sign-in page;
        triggered by CloudFront viewer-request event.
      MemorySize: 128
      Timeout: 1
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'kms:Decrypt'
              Resource: '*'
