AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  An Amazon Kinesis Firehose stream processor that converts input records from
  Apache Common Log format to CSV.
Resources:
  kinesisfirehoseapachelogtocsvpython:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      CodeUri: .
      Description: >-
        An Amazon Kinesis Firehose stream processor that converts input records
        from Apache Common Log format to CSV.
      MemorySize: 128
      Timeout: 3
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:PutItem'
              Resource:
                'Fn::Join':
                  - ''
                  - - 'arn:aws:dynamodb:'
                    - Ref: 'AWS::Region'
                    - ':'
                    - Ref: 'AWS::AccountId'
                    - ':table/*'
            - Effect: Allow
              Action:
                - 'lambda:InvokeFunction'
              Resource:
                'Fn::Join':
                  - ''
                  - - 'arn:aws:lambda:'
                    - Ref: 'AWS::Region'
                    - ':'
                    - Ref: 'AWS::AccountId'
                    - ':function:*'
