AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Monitors VPN connection status of an account in all regions.
Resources:
  vpnconnmonitor:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: monitor_vpn_lambda.lambda_handler
      Runtime: python2.7
      CodeUri: .
      Description: Monitors VPN connection status of an account in all regions.
      MemorySize: 128
      Timeout: 120
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'cloudwatch:PutMetricData'
              Resource: '*'
            - Effect: Allow
              Action:
                - 'ec2:DescribeRegions'
                - 'ec2:DescribeVpnConnections'
              Resource: '*'
