AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Sends an SNS message from input JSON
Resources:
  stepfunctionssendtosns:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.send_to_sns
      Runtime: python2.7
      CodeUri: .
      Description: Sends an SNS message from input JSON
      MemorySize: 128
      Timeout: 3
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'sns:Publish'
              Resource: 'arn:aws:sns:*:*:*'
