regions:
  af-south-1:
    - ServerlessRepo
    - Cognito
    - KMS
    - CodeDeploy
    - XRay
    - IoT
    - GatewayResponses
    - HttpApi
    - ARM
    - MSK
    - MQ
  ap-east-1:
    - Cognito
    - IoT
    - ServerlessRepo
    - HttpApi
    - ARM
  ap-northeast-2:
    - HttpApi
    - ARM
  ap-northeast-3:
    - Cognito
    - IoT
    - ServerlessRepo
    - XRay
    - CodeDeploy
    - HttpApi
    - ARM
    - MSK
    - MQ
    - EFS
    - StateMachineCweCws
    - CodeSign
  ap-south-1:
    - HttpApi
  ap-southeast-3:
    - ServerlessRepo
    - CodeDeploy
    - Cognito
    - GatewayResponses
    - Layers
    - IoT
    - XRay
    - SQS
    - HttpApi
    - UsagePlans
    - MSK
    - MQ
    - Kinesis
    - DynamoDB
    - CodeSign
    - EFS
    - CweCwsDlq
    - StateMachineInlineDefinition
    - StateMachineCweCws
    - StateMachineWithApis
    - LambdaEnvVars
    - ARM
  ap-southeast-1:
    - HttpApi
  ca-central-1:
    - Cognito
    - IoT
    - HttpApi
    - ARM
  cn-north-1:
    - ServerlessRepo
    - Cognito
    - KMS
    - CodeDeploy
    - XRay
    - IoT
    - GatewayResponses
    - HttpApi
    - MSK
    - MQ
    - CodeSign
    - CweCwsDlq
    - Mode
    - ARM
  cn-northwest-1:
    - ServerlessRepo
    - Cognito
    - KMS
    - CodeDeploy
    - XRay
    - IoT
    - GatewayResponses
    - HttpApi
    - ARM
    - MSK
    - MQ
    - CodeSign
    - CweCwsDlq
    - Mode
  eu-north-1:
    - ServerlessRepo
    - Cognito
    - IoT
    - HttpApi
    - Layers
    - ARM
  eu-south-1:
    - ServerlessRepo
    - Cognito
    - KMS
    - CodeDeploy
    - XRay
    - IoT
    - GatewayResponses
    - HttpApi
    - ARM
    - MSK
    - MQ
  eu-west-2:
    - HttpApi
  eu-west-3:
    - Cognito
    - IoT
    - XRay
    - HttpApi
    - ARM
  me-south-1:
    - ServerlessRepo
    - Cognito
    - IoT
    - HttpApi
    - ARM
  sa-east-1:
    - IoT
    - Cognito
    - HttpApi
    - ARM
  us-east-2:
    - HttpApi
  us-gov-east-1:
    - ServerlessRepo
    - Cognito
    - XRay
    - IoT
    - GatewayResponses
    - CodeDeploy
    - HttpApi
    - MSK
    - MQ
    - Kinesis
    - DynamoDB
    - CodeSign
    - CweCwsDlq
    - Mode
    - ARM
  us-gov-west-1:
    - ServerlessRepo
    - Cognito
    - XRay
    - IoT
    - GatewayResponses
    - HttpApi
    - MSK
    - MQ
    - Kinesis
    - DynamoDB
    - CodeSign
    - CweCwsDlq
    - Mode
    - ARM
  us-iso-east-1:
    - ServerlessRepo
    - CodeDeploy
    - Cognito
    - GatewayResponses
    - Layers
    - IoT
    - XRay
    - SQS
    - HttpApi
    - UsagePlans
    - MSK
    - MQ
    - Kinesis
    - DynamoDB
    - CodeSign
    - EFS
    - CweCwsDlq
    - StateMachineInlineDefinition
    - StateMachineCweCws
    - StateMachineWithApis
    - LambdaEnvVars
  us-iso-west-1:
    - ServerlessRepo
    - CodeDeploy
    - Cognito
    - GatewayResponses
    - Layers
    - IoT
    - XRay
    - SQS
    - HttpApi
    - UsagePlans
    - MSK
    - MQ
    - Kinesis
    - DynamoDB
    - CodeSign
    - EFS
    - CweCwsDlq
    - StateMachineInlineDefinition
    - StateMachineCweCws
    - StateMachineWithApis
    - LambdaEnvVars
  us-isob-east-1:
    - ServerlessRepo
    - Cognito
    - CodeDeploy
    - XRay
    - GatewayResponses
    - Layers
    - IoT
    - SQS
    - HttpApi
    - UsagePlans
    - MSK
    - MQ
    - Kinesis
    - DynamoDB
    - CodeSign
    - EFS
    - CweCwsDlq
    - StateMachineInlineDefinition
  us-west-1:
    - Cognito
    - IoT
    - ARM
