AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An Amazon Kinesis stream processor that logs the data being published.
Resources:
  kinesisprocessrecordpython:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      CodeUri: .
      Description: An Amazon Kinesis stream processor that logs the data being published.
      MemorySize: 128
      Timeout: 3
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:PutItem'
              Resource:
                'Fn::Join':
                  - ''
                  - - 'arn:aws:dynamodb:'
                    - Ref: 'AWS::Region'
                    - ':'
                    - Ref: 'AWS::AccountId'
                    - ':table/*'
            - Effect: Allow
              Action:
                - 'lambda:InvokeFunction'
              Resource:
                'Fn::Join':
                  - ''
                  - - 'arn:aws:lambda:'
                    - Ref: 'AWS::Region'
                    - ':'
                    - Ref: 'AWS::AccountId'
                    - ':function:*'
      Events:
        Kinesis1:
          Type: Kinesis
          Properties:
            Stream:
              'Fn::GetAtt':
                - KinesisStream1
                - Arn
            StartingPosition: TRIM_HORIZON
            BatchSize: 100
  KinesisStream1:
    Type: 'AWS::Kinesis::Stream'
    Properties:
      ShardCount: 1
