AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  Provides a simple framework for conducting various tests of your Lambda
  functions.
Resources:
  lambdatestharness:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: .
      Description: >-
        Provides a simple framework for conducting various tests of your Lambda
        functions.
      MemorySize: 128
      Timeout: 60
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:PutItem'
              Resource:
                'Fn::Join':
                  - ''
                  - - 'arn:aws:dynamodb:'
                    - Ref: 'AWS::Region'
                    - ':'
                    - Ref: 'AWS::AccountId'
                    - ':table/*'
            - Effect: Allow
              Action:
                - 'lambda:InvokeFunction'
              Resource:
                'Fn::Join':
                  - ''
                  - - 'arn:aws:lambda:'
                    - Ref: 'AWS::Region'
                    - ':'
                    - Ref: 'AWS::AccountId'
                    - ':function:*'
